version: '3.8'

services:
  backend:
    build: .
    container_name: estoque-backend
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm start
